name: 'Helm 3'
description: 'Helm 3'
branding:
  icon: 'stop-circle'
  color: 'green'
inputs:
  exec:
    description: 'The full helm command to run (including helm)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
